### ISSUE TITLE
MethodBodyObject does not process all of the expressions

### ISSUE THREAD

**Issue by 123a6bcw** [JetBrains-Research/IntelliJDeodorant#11]
For instance:
`for (int i = 0; i < SIZE; i++) {}`
Access to `SIZE` field will be unnoticed, because `MethodBodyObject` does not process expression `PsiForStatement.getCondition()` for `PsiForStatement`.

**Comment by onewhl** [comment]
Resolved in https://github.com/JetBrains-Research/IntelliJDeodorant/pull/24
