### ISSUE TITLE
Filter refactoring opportunities for the files open in the Editor

### ISSUE THREAD

**Issue by tsantalis** [JetBrains-Research/IntelliJDeodorant#19]
The original JDeodorant allows to select specific code elements (packages, Java files, types, methods) to detect refactoring opportunities.
After experimenting with IntelliJDeodorant, I realized that it shows the refactoring opportunities for the entire project. Depending on the project size, we could have hundreds of refactoring opportunities displayed, which may overwhelm the developer.
I suggest to add an option (maybe a checkbox) in the Results to show the refactoring opportunities for the files opened in the editor, or the file the developer currently works on.

**Comment by onewhl** [comment]
Hi,

We made it possible to choose a search scope to detect code smells in 2020.1-1.1. 
Now users can choose the scope of files where the plugin should detect code smells -- All Files, Opened Files, Current File, or some packages/files.
