### ISSUE TITLE
[Feature Envy] Inconsistent results

### ISSUE THREAD

**Issue by tsantalis** [JetBrains-Research/IntelliJDeodorant#21]
I found some inconsistencies in the Move Method refactoring opportunities detected in commit
https://github.com/tsantalis/SOEN6491/commit/e2671cd00cc9a9a60101be0430037201c48b1d60

Only one of the detected refactoring opportunities is common `writeEntryHeader(byte[])`.
Eclipse version reports two additional opportunities:

1. Method: `featureEnvy.jedit.tarEntry.TarEntry::parseTarHeader(TarHeader, byte[]):void`
Target class: `featureEnvy.jedit.tarEntry.TarHeader`
Source/Target accessed members: `0/14`
2. Method: `featureEnvy.jedit.tarEntry.TarEntry::nameTarHeader(TarHeader, String):void`
Target class: `featureEnvy.jedit.tarEntry.TarHeader`
Source/Target accessed members: `0/13`

In these two refactoring opportunities the target object is a parameter of methods `parseTarHeader()` and `nameTarHeader()`

Refactoring opportunities in Eclipse:
![2019-11-16 08_39_40-](https://user-images.githubusercontent.com/1483516/68998186-1a18f980-087d-11ea-90c7-4f35667b8a9a.png)

Refactoring opportunities in IntelliJDeodorant:
![2019-11-16 08_41_40](https://user-images.githubusercontent.com/1483516/68998198-403e9980-087d-11ea-962a-35e8bfb2e915.png)

The opportunity for method `getModTime()` reported by IntelliJDeodorant is a clear false positive.

**Comment by onewhl** [comment]
Fixed.
