### ISSUE TITLE
Do note report methods from tests code in 'Feature Envy'

### ISSUE THREAD

**Issue by turbanoff** [JetBrains-Research/IntelliJDeodorant#25]
I've tried to check my project by 'Feature Envy'.
And noticed that it often suggests to move test-only method to production code. Even JUnit test methods itself.
![image](https://user-images.githubusercontent.com/741251/69094447-691f8400-0a61-11ea-9c8e-21271102fc4c.png)
I think such methods shouldn't be reported.

**Comment by onewhl** [comment]
@turbanoff, thanks! I will fix it.

**Comment by tsantalis** [comment]
Test code is not analyzed for Feature Envy in the Eclipse version of JDeodorant

**Comment by onewhl** [comment]
Fixed.
