### ISSUE TITLE
Feature Envy does not detect all refactoring opportunities 

### ISSUE THREAD

**Issue by lyubortk** [JetBrains-Research/IntelliJDeodorant#30]
IntellijDedorant does not detect a refactoring opportunity in the following code (while the Eclipse version finds one):

Main.java:
```
public class Main {
    public void run3(StringClass stringClass) {
        stringClass.str += "23";
    }
}
```

StringClass.java:
```
public class StringClass {
    public String str = "";
}
```

**Comment by onewhl** [comment]
@lyubortk, yes,I know about the issue and figured out how to fix it. I will commit changes soon.

**Comment by onewhl** [comment]
Fixed.
