### ISSUE TITLE
Error in AbstractMethodFragment

### ISSUE THREAD

**Issue by 123a6bcw** [JetBrains-Research/IntelliJDeodorant#44]
`AbstractMethodFragment` int a line 344 contains:
`TypeObject returnType = TypeObject.extractTypeObject("UNK");`

Which causes a wrong processing of Extract Class Refactoring because of a wrong return type string "UNK". Where should be returnType.getCanonicalText();

**Comment by onewhl** [comment]
Resolved in https://github.com/JetBrains-Research/IntelliJDeodorant/pull/48
