### ISSUE TITLE
Does not find collection adders methods

### ISSUE THREAD

**Issue by 123a6bcw** [JetBrains-Research/IntelliJDeodorant#51]
Method such as 

`List<Object> elements;`
` `
`public void addNewElement(Object element) {`
`    this.elements.add(element)`;
`}`

Won't be considered as a `collectionAdder`, and they are crucial for Extract Class refactoring.

**Comment by onewhl** [comment]
Resolved in https://github.com/JetBrains-Research/IntelliJDeodorant/pull/52
