### ISSUE TITLE
Plugin does not process methods invocations through the local variables.

### ISSUE THREAD

**Issue by 123a6bcw** [JetBrains-Research/IntelliJDeodorant#53]
Which is wrong. It can be reproduced on [RefactoringMiner::ExtractSuperclassRefactoring](https://github.com/tsantalis/RefactoringMiner/blob/master/src/gr/uom/java/xmi/diff/ExtractSuperclassRefactoring.java) class:

Original plugin include in EntitySet for `leftSide()` methods `setDescription` and `setCodeElement`, this plugin dose not.

**Comment by onewhl** [comment]
Resolved in https://github.com/JetBrains-Research/IntelliJDeodorant/pull/52
