### ISSUE TITLE
unreported exception org.apache.commons.configuration2.plist.ParseException; must be caught or declared to be thrown

### ISSUE THREAD

**Issue by Saikiran-Alagatham** [JetBrains-Research/IntelliJDeodorant#77]
Trying to build common configuration, version 2.4 Facing issues with Plist-propertylistConfiguration class.

Cannot resolve symbol 'ParseException'
Cannot resolve symbol 'PropertyListParser'

![Screen Shot 2020-03-28 at 5 27 45 PM](https://user-images.githubusercontent.com/31740497/77880413-96a7e580-722a-11ea-9729-9b45e10ec445.png)
![Screen Shot 2020-03-30 at 2 01 50 AM](https://user-images.githubusercontent.com/31740497/77880415-97407c00-722a-11ea-8052-f70bb44dfd08.png)
![Screen Shot 2020-03-30 at 2 02 22 AM](https://user-images.githubusercontent.com/31740497/77880416-97407c00-722a-11ea-9eb8-1b73331c0741.png)
![Screen Shot 2020-03-30 at 2 02 37 AM](https://user-images.githubusercontent.com/31740497/77880417-97d91280-722a-11ea-8ce7-8b91aee94419.png)

'

**Comment by onewhl** [comment]
Hi, @Saikiran-Alagatham!
First of all, the IntelliJDeodorant builds the project opened in IDE and then start code smell detection **only if there aren't any compilation errors**. If there any errors, the plugin shows them. Judging by a screenshot, you should add some dependencies to your project. 

Best,
Zarina

**Comment by onewhl** [comment]
@Saikiran-Alagatham, anything else I can do for you?

**Comment by Saikiran-Alagatham** [comment]
Thanks for the follow up, the issue was resolved.
