### ISSUE TITLE
FutureEnvy: various buttons have weird disable interaction

### ISSUE THREAD

**Issue by 123a6bcw** [JetBrains-Research/IntelliJDeodorant#8]
`Select all`, `Deselect all` and `Refactor` buttons are active by default on IDEA startup.
`Deselect all` does not become disabled when `Refactor` pressed (unlike `Select all`).
`Refactor` does not become disabled when `Refresh` pressed until all refactorings are calculated (which may take a long time). `Select all` and `Deselect all` probably should be disabled while table refreshing?

et cetera? Need to be checked.

**Comment by onewhl** [comment]
@123a6bcw, good point, let's clarify that.

1). Only `Refresh` button should be active on startup.
2).  `Select all` button should be active only if there are results in table.
3). `Deselect all` button should be active only if one or more suggestions are selected. 
4). `Deselect all` and  `Select all` buttons should be disabled while table is refreshing.
5). `Refactor` button should be active only if one or more suggestions are selected.

**Comment by onewhl** [comment]
The issue was resolved: https://github.com/JetBrains-Research/IntelliJDeodorant/pull/10
