### ISSUE TITLE
Improvement on Refactor - Long method - Allow to customize the template for the method name

### ISSUE THREAD

**Issue by rgamed** [JetBrains-Research/IntelliJDeodorant#80]
The default name `get<varName>()` cold be configurable to something like `create<varName>()` `resolve<varName>()`
Does the template `get<varName>()` comes from the IDE or from the Plugin? Can it be customized? On the team I am part of, the getters should only return a field in a class. A method with `get` should not have logic inside. 

For example `getSpace()` in the image/animation 
![](https://plugins.jetbrains.com/files/14016/screenshot_21392.png)
could be `createSpace()`

**Comment by onewhl** [comment]
Hi @rgamed,

Yeah, you can customize the method name and access modifier as you want.
I would happy to hear feedback about the experience with IntelliJDeodorant if you've already tried. :)

Best,
Zarina

**Comment by onewhl** [comment]
Hi @rgamed,
Anything else can I do for you?

**Comment by rgamed** [comment]
Hi @onewhl, 
from my side this issue can be closed. Thanks for the clarification I have to take a look more in detail. I will came back in case I have some feedback or request the naming options
