### ISSUE TITLE
Output should be sort{ed|able}

### ISSUE THREAD

**Issue by mirabilos** [JetBrains-Research/IntelliJDeodorant#93]
Hi,

the classes in the output should be sorted, and/or the output should be sortable, so it’s easier to find issues in parts of the code one’s responsible for, if you have a very old project (started in 2001) and tons of code and concentrate on only a bit.

**Comment by onewhl** [comment]
Hi, 

Thanks for the feedback, we appreciate it!

We made it possible to choose a search scope to detect code smells in 2020.1-1.1. Please update the plugin to check it out.
Now users can choose the scope of files where the plugin should detect code smells -- All Files, Opened Files, Current File, or some packages/files.

Best,
Zarina

**Comment by onewhl** [comment]
Hi,

Now we show sorted classes in the output for Long Method and God Class. In the case of Feature Envy, the list we show is sortable. Please update the plugin to 2020.1-1.2.

Thanks for the suggestion!
